### ISSUE TITLE
Count LOC for all kind of files

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#142]
We should provide the number of lines for files also when we have no tree-sitter grammar for the language. 
Apparently, this is also not supported by the raw text parser used by CodeCharta.

**Comment by ce-bo** [comment]
We should add the LOC metric in the output for every file that is considered as "not supported". Otherwise it would like like, that we can also calculate other metrics for those files.

Depending on the performance, we might want to introduce a cmd line argument to toggle this behavior. This would not be that important but could help us.
