### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#16]
Release version 1.0.0 as soon as we are ready for it.

**Comment by ResistantBear** [comment]
Orient on CodeCharta to release to npm repository

**Comment by clemens-mw** [comment]
> Orient on CodeCharta to release to npm repository

we can also have a look here: https://github.com/npm/cli/
as another example for production release

**Comment by mylinhdao** [comment]
As suggested hier, I also think that we should extract our import script to a npm run script. The reason is that this script does not affect the end user at all and we don't expect them to adapt the grammar themself. We may implement this change before the release.
> I just thought about making `import-grammars` a npm run script instead of including this into the CLI of the parser? 

 _Originally posted by @clemens-mw in [#305](https://github.com/MaibornWolff/metric-gardener/issues/305#issuecomment-2038287733)_
