### ISSUE TITLE
Add support for Vue

### ISSUE THREAD

**Issue by mylinhdao** [MaibornWolff/metric-gardener#173]
Add support and some tests for Vue

**Comment by ce-bo** [comment]
Open Question was: Whether to support directives with logical operators like and and or.
Answer is: Directive like v-if should be counted, but inline directive code is not needed to be supported because this is not possible out of the box with the vue grammar (inline directive code does not have further node types and is only a string).

**Comment by ResistantBear** [comment]
Closed as not planned because the Vue-grammar is unmaintained and it would require a major refactoring to support files that have to be parsed with multiple grammars. This is the case with Vue, as the grammar requires that the JavaScript part of the code is parsed with the JavaScript grammar instead of the Vue grammar.
