### ISSUE TITLE
Agree upon naming of grammars, grammar expressions, statements, node-types

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#54]
As a Developer and Contributor of metric-gardener, I want to have a clear agreement on the naming of node types / grammar expressions / statements, so that I can name code parts properly and clearly.

ACs:
- We agreed upon a consistent naming for grammars, grammar expressions, statements, node-types.
- There is a definition for these terms in the code.
- Code references are adjusted accordingly (can be done in a separate story).

**Comment by ce-bo** [comment]
I put this to state "new issues" since we need to prepare the decisions needed for this.

**Comment by ResistantBear** [comment]
I had already talked a bit with @mylinhdao when reviewing the import script. I highly recommend to at least rename "expression" to "node type" everywhere to better align with the naming used by tree-sitter and the nodeTypesConfig-file, etc.
I would also suggest to rename the field "expression" inside the nodeTypesConfig to "name" or "type" (at least if we do #103, otherwise, the latter is no option, obviously).
